### ISSUE TITLE
tslib_pibase is not working with TYPO3 6.2

### ISSUE THREAD

**Issue by dhelfer** [Flagbit/TYPO3-changepassword#1]
Fatal error: require_once(): Failed opening required '.../typo3/sysext/cms/tslib/class.tslib_pibase.php' showed up.

**Comment by fredericgaus** [comment]
Dear dhelfer, 

just delete the require_once inside pi1/class.tx_changepassword_pi1.php. After that it should work as expected! 

Best,
Frederic

**Comment by dhelfer** [comment]
Hi Frederic

Thanks for the fast response. I already did that and had to change the extends section too (see pull request)

Regards
Dominique

**Comment by fredericgaus** [comment]
Hi Dominique, 

thanks for the patch. The change of tslib_pibase to AbstractPlugin is not needed. There is a compatibility layer in TYPO3 6.2 for old class names. In TYPO3 7.X this is a bit different, there it could make sense to change the old class name to the new one. 

Regards
Frederic

**Comment by cweiske** [comment]
This should be fixed now that #5 is merged.

**Comment by fredericgaus** [comment]
Issue should be fixed. Please reopen if you think this issue is still valid
